### ISSUE TITLE
Bot Not Processing Self-Sent Messages

### ISSUE THREAD

**Issue by GGontijo** [robertlsc2016/bot-video-downloader#3]
The bot is not processing messages sent by itself. Specifically, if a user is using the account through which the bot initiated WhatsApp Web JS, the bot does not process the messages sent by that user.

**Comment by robertlsc2016** [comment]
thanks for your collaboration. This problem was solved in this commit: https://github.com/robertlsc2016/bot-video-downloader/commit/a8df95e08718f6eebb3306730e2247b8b5374425
